//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Uni_Entities : DbContext
    {
        public Uni_Entities()
            : base("name=Uni_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<uniAlumnos> uniAlumnos { get; set; }
        public virtual DbSet<uniAlumnosDatosPersonales> uniAlumnosDatosPersonales { get; set; }
        public virtual DbSet<uniAlumnosDetalles> uniAlumnosDetalles { get; set; }
        public virtual DbSet<UniAlumnosDetalleTitulo> UniAlumnosDetalleTitulo { get; set; }
        public virtual DbSet<uniEscuelas> uniEscuelas { get; set; }
        public virtual DbSet<UniEscuelasModalidades> UniEscuelasModalidades { get; set; }
        public virtual DbSet<uniTurnosExamenes> uniTurnosExamenes { get; set; }
        public virtual DbSet<uniTurnosHabilitados> uniTurnosHabilitados { get; set; }
        public virtual DbSet<uniEdificios> uniEdificios { get; set; }
        public virtual DbSet<uniPlanes> uniPlanes { get; set; }
        public virtual DbSet<uniPlanesMaterias> uniPlanesMaterias { get; set; }
        public virtual DbSet<uniRegionales> uniRegionales { get; set; }
    
        public virtual ObjectResult<sp_get_UniAlumnos_Result> sp_get_UniAlumnos(Nullable<int> legprovi, Nullable<int> legdef, string username, Nullable<long> docnac)
        {
            var legproviParameter = legprovi.HasValue ?
                new ObjectParameter("legprovi", legprovi) :
                new ObjectParameter("legprovi", typeof(int));
    
            var legdefParameter = legdef.HasValue ?
                new ObjectParameter("legdef", legdef) :
                new ObjectParameter("legdef", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var docnacParameter = docnac.HasValue ?
                new ObjectParameter("docnac", docnac) :
                new ObjectParameter("docnac", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_UniAlumnos_Result>("sp_get_UniAlumnos", legproviParameter, legdefParameter, usernameParameter, docnacParameter);
        }
    
        public virtual ObjectResult<sp_get_UniAlumnos_detalle_Result> sp_get_UniAlumnos_detalle(Nullable<long> cursoEdicionId, Nullable<int> convenioId)
        {
            var cursoEdicionIdParameter = cursoEdicionId.HasValue ?
                new ObjectParameter("cursoEdicionId", cursoEdicionId) :
                new ObjectParameter("cursoEdicionId", typeof(long));
    
            var convenioIdParameter = convenioId.HasValue ?
                new ObjectParameter("convenioId", convenioId) :
                new ObjectParameter("convenioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_UniAlumnos_detalle_Result>("sp_get_UniAlumnos_detalle", cursoEdicionIdParameter, convenioIdParameter);
        }
    
        public virtual ObjectResult<sp_uni_get_datos_alumno_username_Result> sp_uni_get_datos_alumno_username(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_uni_get_datos_alumno_username_Result>("sp_uni_get_datos_alumno_username", usernameParameter);
        }
    
        public virtual ObjectResult<sp_get_PlanesMateriasDetalladasByCodigoPlan_Result> sp_get_PlanesMateriasDetalladasByCodigoPlan(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_PlanesMateriasDetalladasByCodigoPlan_Result>("sp_get_PlanesMateriasDetalladasByCodigoPlan", codigoParameter);
        }
    
        public virtual ObjectResult<sp_KPI_Morosos_Result> sp_KPI_Morosos(Nullable<int> ciclo, Nullable<int> cuatri, Nullable<int> legajo, Nullable<int> sede, string carrera, string nombre, string apellido, Nullable<decimal> dni, Nullable<int> kpi_monto_mayor, Nullable<int> kpi_monto_menor)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var cuatriParameter = cuatri.HasValue ?
                new ObjectParameter("cuatri", cuatri) :
                new ObjectParameter("cuatri", typeof(int));
    
            var legajoParameter = legajo.HasValue ?
                new ObjectParameter("legajo", legajo) :
                new ObjectParameter("legajo", typeof(int));
    
            var sedeParameter = sede.HasValue ?
                new ObjectParameter("sede", sede) :
                new ObjectParameter("sede", typeof(int));
    
            var carreraParameter = carrera != null ?
                new ObjectParameter("carrera", carrera) :
                new ObjectParameter("carrera", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var dniParameter = dni.HasValue ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(decimal));
    
            var kpi_monto_mayorParameter = kpi_monto_mayor.HasValue ?
                new ObjectParameter("kpi_monto_mayor", kpi_monto_mayor) :
                new ObjectParameter("kpi_monto_mayor", typeof(int));
    
            var kpi_monto_menorParameter = kpi_monto_menor.HasValue ?
                new ObjectParameter("kpi_monto_menor", kpi_monto_menor) :
                new ObjectParameter("kpi_monto_menor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KPI_Morosos_Result>("sp_KPI_Morosos", cicloParameter, cuatriParameter, legajoParameter, sedeParameter, carreraParameter, nombreParameter, apellidoParameter, dniParameter, kpi_monto_mayorParameter, kpi_monto_menorParameter);
        }
    
        public virtual ObjectResult<sp_get_alumno_by_legajo_match_Result> sp_get_alumno_by_legajo_match(string legajo)
        {
            var legajoParameter = legajo != null ?
                new ObjectParameter("legajo", legajo) :
                new ObjectParameter("legajo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_alumno_by_legajo_match_Result>("sp_get_alumno_by_legajo_match", legajoParameter);
        }
    
        public virtual ObjectResult<sp_KPI_Inansistencias_Result> sp_KPI_Inansistencias(Nullable<int> ciclo, Nullable<int> cuatri, Nullable<int> legajo, Nullable<int> sede, string carrera, string nombre, string apellido, Nullable<decimal> dni, Nullable<int> kpi_inasistencia_mayor, Nullable<int> kpi_inasistencia_menor)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var cuatriParameter = cuatri.HasValue ?
                new ObjectParameter("cuatri", cuatri) :
                new ObjectParameter("cuatri", typeof(int));
    
            var legajoParameter = legajo.HasValue ?
                new ObjectParameter("legajo", legajo) :
                new ObjectParameter("legajo", typeof(int));
    
            var sedeParameter = sede.HasValue ?
                new ObjectParameter("sede", sede) :
                new ObjectParameter("sede", typeof(int));
    
            var carreraParameter = carrera != null ?
                new ObjectParameter("carrera", carrera) :
                new ObjectParameter("carrera", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var dniParameter = dni.HasValue ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(decimal));
    
            var kpi_inasistencia_mayorParameter = kpi_inasistencia_mayor.HasValue ?
                new ObjectParameter("kpi_inasistencia_mayor", kpi_inasistencia_mayor) :
                new ObjectParameter("kpi_inasistencia_mayor", typeof(int));
    
            var kpi_inasistencia_menorParameter = kpi_inasistencia_menor.HasValue ?
                new ObjectParameter("kpi_inasistencia_menor", kpi_inasistencia_menor) :
                new ObjectParameter("kpi_inasistencia_menor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KPI_Inansistencias_Result>("sp_KPI_Inansistencias", cicloParameter, cuatriParameter, legajoParameter, sedeParameter, carreraParameter, nombreParameter, apellidoParameter, dniParameter, kpi_inasistencia_mayorParameter, kpi_inasistencia_menorParameter);
        }
    
        public virtual ObjectResult<sp_KPI_Examenes_Reprobados_Result> sp_KPI_Examenes_Reprobados(Nullable<int> ciclo, Nullable<int> cuatri, Nullable<int> legajo, Nullable<int> sede, string carrera, string nombre, string apellido, Nullable<decimal> dni, Nullable<int> kpi_reprobados_mayor, Nullable<int> kpi_reprobados_menor)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var cuatriParameter = cuatri.HasValue ?
                new ObjectParameter("cuatri", cuatri) :
                new ObjectParameter("cuatri", typeof(int));
    
            var legajoParameter = legajo.HasValue ?
                new ObjectParameter("legajo", legajo) :
                new ObjectParameter("legajo", typeof(int));
    
            var sedeParameter = sede.HasValue ?
                new ObjectParameter("sede", sede) :
                new ObjectParameter("sede", typeof(int));
    
            var carreraParameter = carrera != null ?
                new ObjectParameter("carrera", carrera) :
                new ObjectParameter("carrera", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var dniParameter = dni.HasValue ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(decimal));
    
            var kpi_reprobados_mayorParameter = kpi_reprobados_mayor.HasValue ?
                new ObjectParameter("kpi_reprobados_mayor", kpi_reprobados_mayor) :
                new ObjectParameter("kpi_reprobados_mayor", typeof(int));
    
            var kpi_reprobados_menorParameter = kpi_reprobados_menor.HasValue ?
                new ObjectParameter("kpi_reprobados_menor", kpi_reprobados_menor) :
                new ObjectParameter("kpi_reprobados_menor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KPI_Examenes_Reprobados_Result>("sp_KPI_Examenes_Reprobados", cicloParameter, cuatriParameter, legajoParameter, sedeParameter, carreraParameter, nombreParameter, apellidoParameter, dniParameter, kpi_reprobados_mayorParameter, kpi_reprobados_menorParameter);
        }
    
        public virtual ObjectResult<sp_KPI_Finales_Reprobados_Result> sp_KPI_Finales_Reprobados(Nullable<int> ciclo, Nullable<int> cuatri, Nullable<int> legajo, Nullable<int> sede, string carrera, string nombre, string apellido, Nullable<decimal> dni, Nullable<int> kpi_reprobados_mayor, Nullable<int> kpi_reprobados_menor)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var cuatriParameter = cuatri.HasValue ?
                new ObjectParameter("cuatri", cuatri) :
                new ObjectParameter("cuatri", typeof(int));
    
            var legajoParameter = legajo.HasValue ?
                new ObjectParameter("legajo", legajo) :
                new ObjectParameter("legajo", typeof(int));
    
            var sedeParameter = sede.HasValue ?
                new ObjectParameter("sede", sede) :
                new ObjectParameter("sede", typeof(int));
    
            var carreraParameter = carrera != null ?
                new ObjectParameter("carrera", carrera) :
                new ObjectParameter("carrera", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var dniParameter = dni.HasValue ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(decimal));
    
            var kpi_reprobados_mayorParameter = kpi_reprobados_mayor.HasValue ?
                new ObjectParameter("kpi_reprobados_mayor", kpi_reprobados_mayor) :
                new ObjectParameter("kpi_reprobados_mayor", typeof(int));
    
            var kpi_reprobados_menorParameter = kpi_reprobados_menor.HasValue ?
                new ObjectParameter("kpi_reprobados_menor", kpi_reprobados_menor) :
                new ObjectParameter("kpi_reprobados_menor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KPI_Finales_Reprobados_Result>("sp_KPI_Finales_Reprobados", cicloParameter, cuatriParameter, legajoParameter, sedeParameter, carreraParameter, nombreParameter, apellidoParameter, dniParameter, kpi_reprobados_mayorParameter, kpi_reprobados_menorParameter);
        }
    }
}
