//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniAlumnosDetalleTitulo
    {
        public int IdEntidad { get; set; }
        public Nullable<int> TipoTituloNivelMedio { get; set; }
        public Nullable<bool> Convalidado { get; set; }
        public string ComentarioTipoTituloNivelMedio { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
