//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniAlumnosDatosPersonales
    {
        public int IdEntidad { get; set; }
        public Nullable<int> TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<bool> Trabaja { get; set; }
        public string EMail { get; set; }
        public string TelFijoCodPais { get; set; }
        public string TelFijoCodArea { get; set; }
        public string TelFijoNumero { get; set; }
        public string TelMovilCodPais { get; set; }
        public string TelMovilCodArea { get; set; }
        public string TelMovilNumero { get; set; }
        public string DirCalle { get; set; }
        public string DirNumero { get; set; }
        public string DirPiso { get; set; }
        public string DirDepto { get; set; }
        public string DirCodigoPostal { get; set; }
        public Nullable<int> DirCodLocalidad { get; set; }
        public Nullable<int> DirCodProvincia { get; set; }
        public Nullable<int> DirCodPais { get; set; }
        public Nullable<System.DateTime> UltimaActualizacion { get; set; }
    }
}
