//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniEdificios
    {
        public string codins { get; set; }
        public string nomins { get; set; }
        public string domins { get; set; }
        public Nullable<int> cantalu { get; set; }
        public string usrnom { get; set; }
        public Nullable<System.DateTime> ftrn { get; set; }
        public Nullable<int> cantlab { get; set; }
        public Nullable<int> canttal { get; set; }
        public Nullable<int> cantaul { get; set; }
        public Nullable<int> cantcli { get; set; }
        public Nullable<int> cantcco { get; set; }
        public Nullable<int> regional { get; set; }
    }
}
