//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniPlanesMaterias
    {
        public string codigo { get; set; }
        public string mater { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<int> cuatri { get; set; }
        public Nullable<int> obliga1 { get; set; }
        public string usrnom { get; set; }
        public Nullable<System.DateTime> ftrn { get; set; }
        public int Fila { get; set; }
        public int TipoMateria { get; set; }
        public bool Idioma { get; set; }
        public Nullable<int> modalidad { get; set; }
        public Nullable<bool> anual { get; set; }
        public Nullable<int> modulosdistancia { get; set; }
        public Nullable<int> clasespresenciales { get; set; }
    }
}
