//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniPlanes
    {
        public string codcar { get; set; }
        public Nullable<int> cantop { get; set; }
        public string nomcar { get; set; }
        public Nullable<System.DateTime> fvig { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<System.DateTime> fcadu { get; set; }
        public Nullable<int> cantmat { get; set; }
        public string usrnom { get; set; }
        public Nullable<System.DateTime> ftrn { get; set; }
        public Nullable<int> c_uniaca { get; set; }
        public Nullable<int> c_titulo { get; set; }
        public string codesc { get; set; }
        public int version { get; set; }
        public Nullable<int> cantidad_anios { get; set; }
        public string Titulo { get; set; }
        public string TituloIntermedio { get; set; }
        public Nullable<int> AnioTituloIntermedio { get; set; }
        public Nullable<bool> publicable { get; set; }
    
        public virtual uniEscuelas uniEscuelas { get; set; }
    }
}
