//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniTurnosHabilitados
    {
        public string codesc { get; set; }
        public string modalidad { get; set; }
        public string turno { get; set; }
        public int regional { get; set; }
        public int anio { get; set; }
        public bool activo { get; set; }
        public string usrnom { get; set; }
        public Nullable<System.DateTime> ftrn { get; set; }
        public int fila { get; set; }
    }
}
