//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniTurnosExamenes
    {
        public int Clave { get; set; }
        public string TurnoExamen { get; set; }
        public string TurnoExamenDescripcion { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<bool> Comun { get; set; }
    }
}
